"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";
import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });
interface IProps {
  children: ReactNode;
  session: any;
}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayoutApp({ session, children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <div className={inter.className}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
