"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";
import { AppProps } from "next/app";
import { BrowserRouter } from "react-router-dom";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayoutApp({ session, children }) {
  return (
    <html lang="en">
      <head>
        <title>CarryU 政大共乘系統</title>
      </head>
      <body>
        <SessionProvider session={session}>
          <div className={inter.className}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
